language: python
os: linux
python:
  - '3.4'
  - '3.5'
  - '3.6'
before_install: |
  if [[ $TRAVIS_OS_NAME == 'osx' ]]; then
    brew update
    # Recommended for pyenv
    brew outdated openssl || brew upgrade openssl
    brew outdated readline || brew upgrade readline
    # Update pyenv
    brew outdated pyenv || brew upgrade pyenv
    # Install specified Python version
    pyenv install $PYTHON
    # Set environment variables
    export PYENV_VERSION=$PYTHON
    export PATH="/Users/travis/.pyenv/shims:${PATH}"
    # Confirm versions
    python --version
    pip -V
  fi
install:
  - pip install --upgrade pip
  - pip install -r requirements/requirements.txt
  - pip install -r requirements/test_requirements.txt
  - pip install .
  - pip freeze
script:
  - pytest
after_success:
  - codecov
jobs:
  include:
  - os: osx
    language: generic
    env: PYTHON=3.4.9
  - os: osx
    language: generic
    env: PYTHON=3.5.6
  - os: osx
    language: generic
    env: PYTHON=3.6.7
    
deploy:
  provider: pypi
  user: zhenwen
  skip_existing: true
  password:
    secure: VcDc6tNT+nuXODwVZsL2J5mPHXjIjEfdOa6vByneJdGKbw94/RDJL31bNYDp/uQj/zUvQu4xrLPpgoobuPD/o2jMgxeGRaoYhA0VGs3kfWGzTzcFSzIYBhtIcP1RUowrxHsGoubi3ERtEK+XgidnDszVd5e2AVeAmh4wJwNK/xLSvSeqplqJ4d8AbfZiDZsMCxT03CUisIRMxRnd4YUlpW83ejecElK1UWaDae2hcbiSVjo3+5n7moUFly1HiKdLJ5R0CH7jNpv8YJxaaWayftTvQdMt2c1tf5whJLKNZm7uVhd0oXM9febxaI5RKpVihI5d3ho/2XrbuXPighH5Sjt1Zr8yExx50mTcvpcmzB7TPkptfOQtKMDMB0uYzUWlqtVMn1Nrzr7QTkVI0hlqMrqGOTz5RI7ljNwOhi9HOu8D8gICw7k4lCE7wk40lws8MOljUXo/xK/R+NCpM091dt3RGQhx3FaZ//PG477E5V3SHeoEBcaFJvWoN7coeykOnXfMxT4rad8DaTi8tHvElBpB/1p7kFGeUa0Uv1MTEeDaykIq6T8HLwYGlkjPPF5af36eiNVHOQ4LMU5XgwWKBqDpNV0alkzH8ohvsPEwK0qUR9PdL7dOYYfS903LDB0rjgOijynnmKkY63XtT40ckKLoVZTCKhUBn4s0SvD3Nvo=
  on:
    branch: master
    