language: python
os: linux
python:
  - '3.4'
  - '3.5'
before_install: |
  if [[ $TRAVIS_OS_NAME == 'osx' ]]; then
    brew update
    # Recommended for pyenv
    brew outdated openssl || brew upgrade openssl
    brew outdated readline || brew upgrade readline
    # Update pyenv
    brew outdated pyenv || brew upgrade pyenv
    # Install specified Python version
    pyenv install $PYTHON
    # Set environment variables
    export PYENV_VERSION=$PYTHON
    export PATH="/Users/travis/.pyenv/shims:${PATH}"
    # Confirm versions
    python --version
    pip -V
  fi
install:
  - pip install --upgrade pip
  - pip install -r requirements/requirements.txt
  - pip install -r requirements/test_requirements.txt
  - pip freeze
script:
  - pytest
after_success:
  - codecov
jobs:
  include:
  - os: osx
    language: generic
    env: PYTHON=3.4.4
  - os: osx
    language: generic
    env: PYTHON=3.5.1
  - os: osx
    language: generic
    env: PYTHON=3.6.6
  - stage: release
    python: '3.6'
    deploy:
      provider: pypi
      server: https://test.pypi.org/legacy/
      user: meissnereric
      password:
        secure: pAWvyarB5bpa1LoeuJUtoAsMizuZbA6maPqfzQ9pcAVZDZJgnx7pZ7uMu/Vu+TfKts7+k0cTW3jNlNnK3ro2FNCD4wGfyqnnCD7eyWpNHrxdl0Pk50z/I6VAVzgMdt7biHopPvP+Dn3ttXJd/SmzDoaEKslYHcIrb4S2/jM+ydqTDwPvBDir/uDT88iMWkIkQ0MTmyTwwsROdLdylDjSpJLlc6I/5+e9jEx6chJRFm2OIoK64zmsfFnF8xA0fdKHDJSDwWQGHpDjw9veC2bBvXEIUsXgHdMuNKK74/8ZaB4gYsl0i8LLKWgL9n43jZKvl7AEK771Kb93IWDpMIiZcV/ae+TgGVatDIVVZ08ubMwj+VrQ59IpB5TnUoEqEjvR6fMbAtrzDvolerJWsigOt/2bebWfZD3tgLhW7jt3G5MbZY1ujawayfEPufV1VyNWCXhM5c0TIFyA/uNnlPf10K1rUhuaa9+dCtnAxlevTSMXqq65+B1oynGFLzeCAJchZQ1SHSs8PG3lysYa9L+EffUGebqJT+YdDEE1t/BvPpGL3bm1ILS9MH3D0OTJUW5TJMSXMcgzi19cdLTfXD/zkHvAA0FksgXug8qsUdJatqXZelAvdv7NjAshcRqgdQcAf36TqzasQOFm7EUcwB1Whl1Fa20yZtcQir8nNmdzano=
      on:
        branch: ci
